// CommonJs, every file is module (by default)
// Modules - Encapsulating Code (only share minimum)
const names = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alternative-flavour')
require("./7-mind-granade")
sayHi("Raf")
sayHi(names.john)
sayHi(names.peter)

console.log(module)